### ISSUE TITLE
Dependency on pry-plus prevents installation on Ruby 2.x

### ISSUE THREAD

**Issue by davidcelis** [baweaver/pry-macro#3]
Pry-plus adds a dependency on `pry-debugger`, which in turn tries to install the `debugger` gem, which does not build on Rubies greater than 1.9.x. The solution for many in this case has been to switch to byebug. Anyway, in this current inception, pry-macro is not usable on Ruby 2.

**Comment by baweaver** [comment]
I'll get this taken care of tonight.

**Comment by baweaver** [comment]
Fix: https://github.com/baweaver/pry-macro/commit/7de194f0593dedde1607b8ec16a927abc4757e1d

1.0.1 release is live with this fix.

**Comment by davidcelis** [comment]
That was fast! Thanks! :sparkles:
